Algoritmo "atividade14"
// Disciplina   : [Lógica de Programação com javascript]
// Professor   : Jailson

// Descricao: Verificar se um valor digitado pelo usuário
//  é maior que 10 e exibir mensagem adequada


// Autor(a)    : Marcos
// Data atual  : 26/03/2025
var
   valor: real
inicio
   escreva("Digite um valor: ")
   leia(valor)

   se valor > 10 entao
      escreval("É MAIOR QUE 10!")
   senao
      escreval("NÃO É MAIOR QUE 10!")
   fimse
fimalgoritmo