Algoritmo "manzanoPag41Ex4k"

// Disciplina   : [Lógica de Programação com javascript]
// Professor   : Jailson

// Descrição   :   Lê um determinado valor inteiro, e efetua a sua
//apresentação, caso o valor não seja maior que três.

// Autor(a)    : marcos
// Data atual  : 30/03/2025

Var
   valor: Inteiro
Inicio
   Escreva("Digite um inteiro: ")
   Leia(valor)

   Se (valor <= 3) Entao
      Escreva("O inteiro é: ", valor)
   FimSe
FimAlgoritmo