Algoritmo "manzanoPag66Exe1E"
// Disciplina   : [Lógica de Programação com javascript]
// Professor   : Jailson
// Descrição   :  exibe todos os números ímpares de 0 a 20
// Autor(a)    : Marcos Vinicius
// Data atual  : 01/04/2025
var
   contador: inteiro
inicio
      escreval("Ímpares de 0 a 10:")

      para contador de 0 ate 20 faca
          se (contador % 2 <> 0) entao
             escreva(contador, " ")
          fimse
      fimpara

      escreval("")
fimalgoritmo