Algoritmo "manzanoPag66Exe1C"
// Disciplina   : [Lógica de Programação com javascript]
// Professor   : Jailson
// Descrição   : calcula a soma dos 100 primeiros números inteiros
// Autor(a)    : Marcos Vinicius
// Data atual  : 01/04/2025
var
   contador, soma: inteiro
inicio
      soma <- 0  

      para contador de 1 ate 100 faca
          soma <- soma + contador
      fimpara

      escreval("A soma dos 100 primeiros números inteiros é: ", soma)
fimalgoritmo