Algoritmo "manzano7b"
// Disciplina   : [Lógica de Programação com javascript]
// Professor   : Jailson 
// Descrição   : converte Fahrenheit (°F) para Celsius (°C)
// Autor(a)    : Marcos
// Data atual  : 29/03/2025
var

   Fahrenheit, Celsius: real
   
inicio

   escreva("Fahrenheit (°F): ")
   leia(Fahrenheit)

   Celsius <- (Fahrenheit - 32) * (5 / 9)

   escreval("")
   escreval(Fahrenheit:5:2, "°F da ", Celsius:5:2, "°C")
   escreval("")
   
fimalgoritmo