Algoritmo "manzano7a"
// Disciplina   : [Lógica de Programação com javascript]
// Professor   : Jailson 
// Descrição   : lê uma temperatura em graus Celsius e a converte para Fahrenheit
// Autor(a)    : Marcos
// Data atual  : 29/03/2025
var
   C, F: real
inicio
   escreva("Digite a temperatura em graus Celsius: ")
   leia(C)

   F <- (9 * C + 160) / 5

   escreval("A temperatura em graus Fahrenheit é: ", F)
fimalgoritmo