Algoritmo "atividadeJailson05"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson 

// Descrição   : Exibe todos os números pares de 2 a 20 utilizando laço enquanto

// Autor(a)    : Marcos
// Data atual  : 28/03/2025
var
   numero: inteiro

inicio
   numero <- 2

   escreval("   NÚMEROS PARES DE 2 A 20")

   enquanto numero <= 20 faca
      escreva(numero, " ")
      numero <- numero + 2
   fimenquanto

   escreval("")
fimalgoritmo